# bash commands
alias la='ll' # remap
alias rmrf='rm -rf' # force remove a folder
alias take='function _take() { mkdir -p "$1" && cd "$1"; }; _take' # MacOS 'take' command

# Git commands from ohmyzsh
alias g='git'
alias gcl='g clone --recurse-submodules && cd "$1"'
alias ga='g add'
alias gaa='g add --all'
alias gba='g branch --all'
alias gbr='g branch --remote'
alias ggsup='g branch --set-upstream-to=origin/'
alias gco='g checkout'
alias gcor='g checkout --recurse-submodules'
alias gcb='g checkout -b'
alias gcp='g cherry-pick'
alias gcpa='g cherry-pick --abort'
alias gcpc='g cherry-pick --continue'
alias gcl='g clone --recurse-submodules'
alias gc='g commit --verboase'
alias gcmsg='g commit --message'
alias gcam='g commit --al --message'
alias gcf='g config --list'
alias gf='git fetch'
alias gfo='gf origin'
alias gfa='g fetch --all --prune'
alias gl='g log'
alias glg='gl --graph'
alias glgm='gl --graph --max-count=10'
alias gm='git merge'
alias gpull='g pull'
alias gpr='g pull --rebase'
alias gprv='g pull --rebase -v'
alias gpra='g pull --rebase --autostash -v'
alias gpush='g push'
alias gpd='g push --dry-run'
alias grebase='git rebase'
alias gra='g rebase --abort'
alias grc='g rebase --continue'
alias grs='g rebase --skip'
alias gr='git remote'
alias grv='git remote --verbose'
alias gra='git remote add'
alias grrm='git remote remove'
alias grmv='git remote rename'
alias grset='git remote set-url'
alias gstash='g stash'
alias gsa='g stash --all'
alias gsp='g stash pop'
alias gsl='g stash list'
alias gst='g status'
alias gss='g status --short'
alias gssb='g status --short -b'
